/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface AeDevlistComponent {

    }

    interface AeIconsComponent {
      'color': string;
      'name': string;
      'size': string;
    }

    interface AeLogoComponent {
      'firstcolor': string;
      'secondcolor': string;
    }

    interface AeSpinnerComponent {
      'color': string;
      'colortwo': string;
      'type': string;
    }

    interface AeSvgComponent {
      'id': string;
      'url': string;
      'wide': string;
    }
  }


    interface HTMLAeDevlistComponentElement extends StencilComponents.AeDevlistComponent, HTMLStencilElement {}

    var HTMLAeDevlistComponentElement: {
      prototype: HTMLAeDevlistComponentElement;
      new (): HTMLAeDevlistComponentElement;
    };
    

    interface HTMLAeIconsComponentElement extends StencilComponents.AeIconsComponent, HTMLStencilElement {}

    var HTMLAeIconsComponentElement: {
      prototype: HTMLAeIconsComponentElement;
      new (): HTMLAeIconsComponentElement;
    };
    

    interface HTMLAeLogoComponentElement extends StencilComponents.AeLogoComponent, HTMLStencilElement {}

    var HTMLAeLogoComponentElement: {
      prototype: HTMLAeLogoComponentElement;
      new (): HTMLAeLogoComponentElement;
    };
    

    interface HTMLAeSpinnerComponentElement extends StencilComponents.AeSpinnerComponent, HTMLStencilElement {}

    var HTMLAeSpinnerComponentElement: {
      prototype: HTMLAeSpinnerComponentElement;
      new (): HTMLAeSpinnerComponentElement;
    };
    

    interface HTMLAeSvgComponentElement extends StencilComponents.AeSvgComponent, HTMLStencilElement {}

    var HTMLAeSvgComponentElement: {
      prototype: HTMLAeSvgComponentElement;
      new (): HTMLAeSvgComponentElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'ae-devlist-component': JSXElements.AeDevlistComponentAttributes;
    'ae-icons-component': JSXElements.AeIconsComponentAttributes;
    'ae-logo-component': JSXElements.AeLogoComponentAttributes;
    'ae-spinner-component': JSXElements.AeSpinnerComponentAttributes;
    'ae-svg-component': JSXElements.AeSvgComponentAttributes;
    }
  }

  namespace JSXElements {

    export interface AeDevlistComponentAttributes extends HTMLAttributes {
      'onOnToggle'?: (event: CustomEvent) => void;
    }

    export interface AeIconsComponentAttributes extends HTMLAttributes {
      'color'?: string;
      'name'?: string;
      'size'?: string;
    }

    export interface AeLogoComponentAttributes extends HTMLAttributes {
      'firstcolor'?: string;
      'secondcolor'?: string;
    }

    export interface AeSpinnerComponentAttributes extends HTMLAttributes {
      'color'?: string;
      'colortwo'?: string;
      'type'?: string;
    }

    export interface AeSvgComponentAttributes extends HTMLAttributes {
      'id'?: string;
      'url'?: string;
      'wide'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'ae-devlist-component': HTMLAeDevlistComponentElement
    'ae-icons-component': HTMLAeIconsComponentElement
    'ae-logo-component': HTMLAeLogoComponentElement
    'ae-spinner-component': HTMLAeSpinnerComponentElement
    'ae-svg-component': HTMLAeSvgComponentElement
  }

  interface ElementTagNameMap {
    'ae-devlist-component': HTMLAeDevlistComponentElement;
    'ae-icons-component': HTMLAeIconsComponentElement;
    'ae-logo-component': HTMLAeLogoComponentElement;
    'ae-spinner-component': HTMLAeSpinnerComponentElement;
    'ae-svg-component': HTMLAeSvgComponentElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

